// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Merchant.proto

package com.redteamobile.scloud;

public interface CheckSignRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CheckSignResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>optional string except = 2;</code>
   */
  java.lang.String getExcept();
  /**
   * <code>optional string except = 2;</code>
   */
  com.google.protobuf.ByteString
      getExceptBytes();

  /**
   * <code>optional string request_id = 3;</code>
   */
  java.lang.String getRequestId();
  /**
   * <code>optional string request_id = 3;</code>
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();
}
