// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Merchant.proto

package com.redteamobile.scloud;

public interface MerchantInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MerchantInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string code = 2;</code>
   */
  java.lang.String getCode();
  /**
   * <code>optional string code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>optional .Merchant.MerchantStatus status = 3;</code>
   */
  int getStatusValue();
  /**
   * <code>optional .Merchant.MerchantStatus status = 3;</code>
   */
  com.redteamobile.scloud.Merchant.MerchantStatus getStatus();

  /**
   * <code>optional string name = 4;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 channel_id = 5;</code>
   */
  int getChannelId();
}
