// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Merchant.proto

package com.redteamobile.scloud;

public interface QueryMerchantReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:QueryMerchantReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string merchant_code = 1;</code>
   */
  java.lang.String getMerchantCode();
  /**
   * <code>optional string merchant_code = 1;</code>
   */
  com.google.protobuf.ByteString
      getMerchantCodeBytes();
}
